### ISSUE TITLE
CI run failed in VCS(git) package

### ISSUE THREAD

**Issue by cubercsl** [ouuan/AUR-template#3]
1. `git clean` can not clean `src` directory.
Failed in: https://github.com/2014CAIS01/AUR-packages/runs/2056864144

2. If upstream update the code,  `$pkgver` will be changed in `check PKGBUILD` and fail.
https://github.com/2014CAIS01/AUR-packages/runs/2065355972

**Comment by ouuan** [comment]
The first one is fixed.

The second failure is expected, but there can be a feature request for auto-updating the version when the result of `pkgver` is changed.
